export const lines = [
  { Line: 'A', color: 'blue' },
  { Line: 'B', color: 'orange' },
  { Line: 'C', color: 'blue' },
  { Line: 'D', color: 'orange' },
  { Line: 'E', color: 'blue' },
  { Line: 'F', color: 'orange' },
  { Line: 'G', color: 'lightgreen' },
  { Line: 'J', color: 'brown' },
  { Line: 'L', color: 'grey' },
  { Line: 'M', color: 'orange' },
  { Line: 'N', color: 'yellow' },
  { Line: 'Q', color: 'yellow' },
  { Line: 'R', color: 'yellow' },
  { Line: 'S', color: 'grey' },
  { Line: 'Z', color: 'brown' },
  { Line: '1', color: 'red' },
  { Line: '2', color: 'red' },
  { Line: '3', color: 'red' },
  { Line: '4', color: 'green' },
  { Line: '5', color: 'green' },
  { Line: '6', color: 'green' },
  { Line: '7', color: 'purple' },
];
